### PR TITLE
Exit terminal app

### PR DESCRIPTION
**Pull request by max-lt**
On linux (at least) the example app get stuck when exiting with Ctrl + C

### CODE REVIEW

**Comment by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [comment]
I also noticed that some apps require pressing ctrl+c twice to exit them. Others work as expected

**Comment by mafintosh** [comment]
Once fires the teardown, you should wait for that to finish. If it doesnt finish prop a but in whatever is using teardown

**Comment by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [comment]
I actually did `swarm.destroy` instead of `swarm.destroy()` I blame missing types not myself. Jk

**Comment by mafintosh** [comment]
Awesome, glad you got it fixed

**Comment by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [comment]
I need to correct myself. The example this PR is related to indeed does crash after pressing `ctrl` + `c` 

No way to recover the terminal. Only killing it helps.

Haven't tested the fix suggested in this PR.

**Comment by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [comment]
The proposed solution works kinda. But `Pear.teardown()` doesn't appear to be triggered

**Comment by max-lt** [comment]
@d61b292b-2859-4ed6-8c7c-b7397ad8e351 the app does not really crash, it's just that CTRL+C is captured by the raw input mode, you have at least to reset it to normal mode to be able to force exit (by pressing CTRL+C again) the program.

**Comment by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [comment]
My comment was just a minor nitpick. But we can agree that it shouldn't take a month to get this simple fix merged. If it had been merged I didn't have to deal with this problem at all and people coming after me shouldn't either

**Comment by rafapaezbas** [comment]
adressed here https://github.com/holepunchto/pear-docs/pull/134/commits/ccfe5aacbfdf530be21d80777fcdc6e00feaa9f6. The solution in this PR is not optimal because the closing logic of the app should be only in teardown function.

**Pull request closed without merging**
