### PR TITLE
Update making-a-pear-desktop-app.md

### PR DESCRIPTION
**Pull request by mattdesl**
add note about running two pear apps

### CODE REVIEW

**Comment by dabuchera** [comment]
In addition it would be good to make the electron windows draggable during development too.

**Comment by mafintosh** [comment]
@dabuchera will cc @davidmarkclements on that one

**Comment by dabuchera** [comment]
@mafintosh Again Windows only bug. Ubuntu is draggable.

**Comment by mafintosh** [comment]
cc @davidmarkclements

**Pull request merged**
